name: Rust CI

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Rust
      uses: actions-rs/toolchain@v1  # This is an alternative to actions/setup-rust
      with:
        toolchain: stable

    - name: Build, Test, and Run
      run: |
        cargo build --verbose
        cargo test --verbose
        cargo run  # Add any additional run options as needed
